import {getTranslations} from "next-intl/server";

export const getIndexLanguageText = async () => {
  const tIndex = await getTranslations('IndexPage');
  return {
    title: tIndex('title'),
    description: tIndex('description'),
    keywords: tIndex('keywords'),
    loadingText: tIndex('loadingText'),
    placeholderText: tIndex('placeholderText'),
  };
}

export const getTextCleanText = async () => {
  const textClean = await getTranslations('textClean');
  return {
    h1: textClean('h1'),
    h1_desc: textClean('h1_desc'),
    wrap_lines: textClean('wrap_lines'),
    default_text: textClean('default_text'),
    show_char: textClean('show_char'),
    show_word: textClean('show_word'),
    common_remove_extra_sapces: textClean('common_remove_extra_sapces'),
    common_remove_empty_lines: textClean('common_remove_empty_lines'),
    common_remove_line_breaks: textClean('common_remove_line_breaks'),
    common_uppercase_all: textClean('common_uppercase_all'),
    common_lowercase_all: textClean('common_lowercase_all'),
    common_capitalize_sentences: textClean('common_capitalize_sentences'),
    common_capitalize_words: textClean('common_capitalize_words'),
    common_remove_duplicate_lines: textClean('common_remove_duplicate_lines'),
    common_copy: textClean('common_copy'),
    common_clear: textClean('common_clear'),
    select_all: textClean('select_all'),
    select_none: textClean('select_none'),
    select_default: textClean('select_default'),
    char_setting: textClean('char_setting'),
    char_remove_puctuation_marks: textClean('char_remove_puctuation_marks'),
    char_strip_all_emojis: textClean('char_strip_all_emojis'),
    char_remove_non_ascii_characters: textClean('char_remove_non_ascii_characters'),
    char_remove_non_alphanumeric_characters: textClean('char_remove_non_alphanumeric_characters'),
    char_remove_all_emails: textClean('char_remove_all_emails'),
    multiple_line_setting: textClean('multiple_line_setting'),
    line_add: textClean('line_add'),
    line_remove: textClean('line_remove'),
    line_to_left: textClean('line_to_left'),
    line_to_right: textClean('line_to_right'),
    line_from_left: textClean('line_from_left'),
    line_from_right: textClean('line_from_right'),
    html_setting: textClean('html_setting'),
    html_unexcape_html_tags: textClean('html_unexcape_html_tags'),
    html_remove_all_html_tags: textClean('html_remove_all_html_tags'),
    html_remove_all_ids: textClean('html_remove_all_ids'),
    html_remove_all_classes: textClean('html_remove_all_classes'),
    html_decode_html_character_entities: textClean('html_decode_html_character_entities'),
    html_decode_url_encoded_characters: textClean('html_decode_url_encoded_characters'),
    find_replace_setting: textClean('find_replace_setting'),
    find_find: textClean('find_find'),
    find_replace: textClean('find_replace'),
    find_replace_text: textClean('find_replace_text'),
    find_replace_with_tab: textClean('find_replace_with_tab'),
    find_replace_with_space: textClean('find_replace_with_space'),
    find_replace_space: textClean('find_replace_space'),
    text_clean_apply: textClean('text_clean_apply'),
    h2_1: textClean('h2_1'),
    h2_1_p: textClean('h2_1_p'),
    h2_2: textClean('h2_2'),
    h2_2_p: textClean('h2_2_p'),
    h2_2_h3_1: textClean('h2_2_h3_1'),
    h2_2_h3_1_p: textClean('h2_2_h3_1_p'),
    h2_2_h3_2: textClean('h2_2_h3_2'),
    h2_2_h3_2_p: textClean('h2_2_h3_2_p'),
    h2_2_h3_2_h4_1: textClean('h2_2_h3_2_h4_1'),
    h2_2_h3_2_h4_1_p: textClean('h2_2_h3_2_h4_1_p'),
    h2_2_h3_2_h4_2: textClean('h2_2_h3_2_h4_2'),
    h2_2_h3_2_h4_2_p: textClean('h2_2_h3_2_h4_2_p'),
    h2_2_h3_2_h4_3: textClean('h2_2_h3_2_h4_3'),
    h2_2_h3_2_h4_3_p: textClean('h2_2_h3_2_h4_3_p'),
    h2_2_h3_2_h4_4: textClean('h2_2_h3_2_h4_4'),
    h2_2_h3_2_h4_4_p: textClean('h2_2_h3_2_h4_4_p'),
    h2_2_h3_3: textClean('h2_2_h3_3'),
    h2_2_h3_3_p: textClean('h2_2_h3_3_p'),
    h2_2_h3_4: textClean('h2_2_h3_4'),
    h2_2_h3_4_p: textClean('h2_2_h3_4_p'),
    h2_3: textClean('h2_3'),
    h2_3_p_1: textClean('h2_3_p_1'),
    h2_3_h3_1: textClean('h2_3_h3_1'),
    h2_3_h3_1_h4_1: textClean('h2_3_h3_1_h4_1'),
    h2_3_h3_1_h4_1_p: textClean('h2_3_h3_1_h4_1_p'),
    h2_3_h3_1_h4_2: textClean('h2_3_h3_1_h4_2'),
    h2_3_h3_1_h4_2_p: textClean('h2_3_h3_1_h4_2_p'),
    h2_3_h3_1_h4_3: textClean('h2_3_h3_1_h4_3'),
    h2_3_h3_1_h4_3_p: textClean('h2_3_h3_1_h4_3_p'),
    h2_3_h3_1_h4_4: textClean('h2_3_h3_1_h4_4'),
    h2_3_h3_1_h4_4_p: textClean('h2_3_h3_1_h4_4_p'),
    h2_3_h3_1_h4_5: textClean('h2_3_h3_1_h4_5'),
    h2_3_h3_1_h4_5_p: textClean('h2_3_h3_1_h4_5_p'),
    h2_3_h3_2: textClean('h2_3_h3_2'),
    h2_3_h3_2_h4_1: textClean('h2_3_h3_2_h4_1'),
    h2_3_h3_2_h4_1_p: textClean('h2_3_h3_2_h4_1_p'),
    h2_3_h3_2_h4_2: textClean('h2_3_h3_2_h4_2'),
    h2_3_h3_2_h4_2_p: textClean('h2_3_h3_2_h4_2_p'),
    h2_3_h3_2_h4_3: textClean('h2_3_h3_2_h4_3'),
    h2_3_h3_2_h4_3_p: textClean('h2_3_h3_2_h4_3_p'),
    h2_3_h3_2_h4_4: textClean('h2_3_h3_2_h4_4'),
    h2_3_h3_2_h4_4_p: textClean('h2_3_h3_2_h4_4_p'),
    h2_3_h3_2_h4_5: textClean('h2_3_h3_2_h4_5'),
    h2_3_h3_2_h4_5_p: textClean('h2_3_h3_2_h4_5_p'),
    h2_3_h3_2_h4_6: textClean('h2_3_h3_2_h4_6'),
    h2_3_h3_2_h4_6_p: textClean('h2_3_h3_2_h4_6_p'),
    h2_3_h3_3: textClean('h2_3_h3_3'),
    h2_3_h3_3_h4_1: textClean('h2_3_h3_3_h4_1'),
    h2_3_h3_3_h4_1_p: textClean('h2_3_h3_3_h4_1_p'),
    h2_3_h3_3_h4_2: textClean('h2_3_h3_3_h4_2'),
    h2_3_h3_3_h4_2_p: textClean('h2_3_h3_3_h4_2_p'),
    h2_3_h3_3_h4_3: textClean('h2_3_h3_3_h4_3'),
    h2_3_h3_3_h4_3_p: textClean('h2_3_h3_3_h4_3_p'),
    h2_3_h3_3_h4_4: textClean('h2_3_h3_3_h4_4'),
    h2_3_h3_3_h4_4_p: textClean('h2_3_h3_3_h4_4_p'),
    h2_3_h3_4: textClean('h2_3_h3_4'),
    h2_3_h3_4_h4_1: textClean('h2_3_h3_4_h4_1'),
    h2_3_h3_4_h4_1_p: textClean('h2_3_h3_4_h4_1_p'),
    h2_3_h3_4_h4_2: textClean('h2_3_h3_4_h4_2'),
    h2_3_h3_4_h4_2_p: textClean('h2_3_h3_4_h4_2_p'),
    h2_3_h3_4_h4_3: textClean('h2_3_h3_4_h4_3'),
    h2_3_h3_4_h4_3_p: textClean('h2_3_h3_4_h4_3_p'),
    h2_3_h3_5: textClean('h2_3_h3_5'),
    h2_3_h3_5_h4_1: textClean('h2_3_h3_5_h4_1'),
    h2_3_h3_5_h4_1_p: textClean('h2_3_h3_5_h4_1_p'),
    h2_3_h3_5_h4_2: textClean('h2_3_h3_5_h4_2'),
    h2_3_h3_5_h4_2_p: textClean('h2_3_h3_5_h4_2_p'),
    h2_3_h3_5_h4_3: textClean('h2_3_h3_5_h4_3'),
    h2_3_h3_5_h4_3_p: textClean('h2_3_h3_5_h4_3_p'),
    h2_3_h3_5_h4_4: textClean('h2_3_h3_5_h4_4'),
    h2_3_h3_5_h4_4_p: textClean('h2_3_h3_5_h4_4_p'),
    h2_3_h3_5_h4_5: textClean('h2_3_h3_5_h4_5'),
    h2_3_h3_5_h4_5_p: textClean('h2_3_h3_5_h4_5_p'),
    h2_3_h3_5_h4_6: textClean('h2_3_h3_5_h4_6'),
    h2_3_h3_5_h4_6_p: textClean('h2_3_h3_5_h4_6_p'),
    h2_3_h3_5_h4_7: textClean('h2_3_h3_5_h4_7'),
    h2_3_h3_5_h4_7_p: textClean('h2_3_h3_5_h4_7_p'),
    h2_3_h3_5_h4_8: textClean('h2_3_h3_5_h4_8'),
    h2_3_h3_5_h4_8_p: textClean('h2_3_h3_5_h4_8_p'),
    h2_3_h3_5_h4_9: textClean('h2_3_h3_5_h4_9'),
    h2_3_h3_5_h4_9_p: textClean('h2_3_h3_5_h4_9_p'),
    h2_3_h3_5_h4_10: textClean('h2_3_h3_5_h4_10'),
    h2_3_h3_5_h4_10_p: textClean('h2_3_h3_5_h4_10_p'),
    h2_3_p_2: textClean('h2_3_p_2')
  };
}

export const getPrivacyPolicyLanguageText = async () => {
  const tPrivacyPolicy = await getTranslations('privacyPolicy');
  return {
    title: tPrivacyPolicy('title'),
    description: tPrivacyPolicy('description'),
    h1: tPrivacyPolicy('h1'),
    date: tPrivacyPolicy('date'),
    desc: tPrivacyPolicy('desc'),
    h4_1: tPrivacyPolicy('h4_1'),
    h4_1_pa: tPrivacyPolicy('h4_1_pa'),
    h4_1_pb: tPrivacyPolicy('h4_1_pb'),
    h4_2: tPrivacyPolicy('h4_2'),
    h4_2_p: tPrivacyPolicy('h4_2_p'),
    h4_3: tPrivacyPolicy('h4_3'),
    h4_3_p: tPrivacyPolicy('h4_3_p'),
    h4_4: tPrivacyPolicy('h4_4'),
    h4_4_p: tPrivacyPolicy('h4_4_p'),
    h4_5: tPrivacyPolicy('h4_5'),
    h4_5_p: tPrivacyPolicy('h4_5_p'),
    h4_6: tPrivacyPolicy('h4_6'),
    h4_6_p: tPrivacyPolicy('h4_6_p'),
  }
}

export const getTermsOfServiceLanguageText = async () => {
  const tTermsOfService = await getTranslations('termsOfService');
  return {
    title: tTermsOfService('title'),
    description: tTermsOfService('description'),
    h1: tTermsOfService('h1'),
    date: tTermsOfService('date'),
    desc: tTermsOfService('desc'),
    h4_1: tTermsOfService('h4_1'),
    h4_1_p: tTermsOfService('h4_1_p'),
    h4_2: tTermsOfService('h4_2'),
    h4_2_p: tTermsOfService('h4_2_p'),
    h4_3: tTermsOfService('h4_3'),
    h4_3_p: tTermsOfService('h4_3_p'),
    h4_4: tTermsOfService('h4_4'),
    h4_4_p: tTermsOfService('h4_4_p'),
    h4_5: tTermsOfService('h4_5'),
    h4_5_p: tTermsOfService('h4_5_p'),
    h4_6: tTermsOfService('h4_6'),
    h4_6_p: tTermsOfService('h4_6_p'),
  }
}

export async function getDeleteFormatText() {
  const deleteFormat = await getTranslations('deleteFormat');
  return {
    title: deleteFormat('title'),
    description: deleteFormat('description'),
    keywords: deleteFormat('keywords'),
    h1: deleteFormat('h1'),
    h1_desc: deleteFormat('h1_desc'),
    default_text: deleteFormat('default_text'),
    copy: deleteFormat('copy'),
    clear: deleteFormat('clear'),
    format_settings: deleteFormat('format_settings'),
    remove_spaces: deleteFormat('remove_spaces'),
    remove_newlines: deleteFormat('remove_newlines'),
    remove_formatting: deleteFormat('remove_formatting'),
    remove_indentation: deleteFormat('remove_indentation'),
    apply: deleteFormat('apply'),
    about_title: deleteFormat('about_title'),
    about_desc: deleteFormat('about_desc'),
    features_title: deleteFormat('features_title'),
    feature_1_title: deleteFormat('feature_1_title'),
    feature_1_desc: deleteFormat('feature_1_desc'),
    feature_2_title: deleteFormat('feature_2_title'),
    feature_2_desc: deleteFormat('feature_2_desc'),
    feature_3_title: deleteFormat('feature_3_title'),
    feature_3_desc: deleteFormat('feature_3_desc'),
    feature_4_title: deleteFormat('feature_4_title'),
    feature_4_desc: deleteFormat('feature_4_desc'),
    feature_5_title: deleteFormat('feature_5_title'),
    feature_5_desc: deleteFormat('feature_5_desc'),
    feature_6_title: deleteFormat('feature_6_title'),
    feature_6_desc: deleteFormat('feature_6_desc'),
    faq_title: deleteFormat('faq_title'),
    faq_1_title: deleteFormat('faq_1_title'),
    faq_1_desc: deleteFormat('faq_1_desc'),
    faq_2_title: deleteFormat('faq_2_title'),
    faq_2_desc: deleteFormat('faq_2_desc'),
    faq_3_title: deleteFormat('faq_3_title'),
    faq_3_desc: deleteFormat('faq_3_desc'),
    faq_4_title: deleteFormat('faq_4_title'),
    faq_4_desc: deleteFormat('faq_4_desc'),
    faq_5_title: deleteFormat('faq_5_title'),
    faq_5_desc: deleteFormat('faq_5_desc'),
    faq_6_title: deleteFormat('faq_6_title'),
    faq_6_desc: deleteFormat('faq_6_desc')
  };
}

export const getFormatHtmlText = async () => {
  const t = await getTranslations('formatHtml');
  return {
    title: t('title'),
    description: t('description'),
    keywords: t('keywords'),
    h1: t('h1'),
    h1_desc: t('h1_desc'),
    default_text: t('default_text'),
    format: t('format'),
    copy: t('copy'),
    clear: t('clear'),
    about_title: t('about_title'),
    about_desc: t('about_desc'),
    features_title: t('features_title'),
    feature_1_title: t('feature_1_title'),
    feature_1_desc: t('feature_1_desc'),
    feature_2_title: t('feature_2_title'),
    feature_2_desc: t('feature_2_desc'),
    feature_3_title: t('feature_3_title'),
    feature_3_desc: t('feature_3_desc'),
    feature_4_title: t('feature_4_title'),
    feature_4_desc: t('feature_4_desc'),
    feature_5_title: t('feature_5_title'),
    feature_5_desc: t('feature_5_desc'),
    faq_title: t('faq_title'),
    faq_1_title: t('faq_1_title'),
    faq_1_desc: t('faq_1_desc'),
    faq_2_title: t('faq_2_title'),
    faq_2_desc: t('faq_2_desc'),
    faq_3_title: t('faq_3_title'),
    faq_3_desc: t('faq_3_desc'),
    faq_4_title: t('faq_4_title'),
    faq_4_desc: t('faq_4_desc'),
    faq_5_title: t('faq_5_title'),
    faq_5_desc: t('faq_5_desc'),
    faq_6_title: t('faq_6_title'),
    faq_6_desc: t('faq_6_desc')
  };
};

export const getRemoveDuplicatesText = async () => {
  const removeDuplicates = await getTranslations('removeDuplicates');
  return {
    title: removeDuplicates('title'),
    description: removeDuplicates('description'),
    keywords: removeDuplicates('keywords'),
    h1: removeDuplicates('h1'),
    h1_desc: removeDuplicates('h1_desc'),
    default_text: removeDuplicates('default_text'),
    copy: removeDuplicates('copy'),
    clear: removeDuplicates('clear'),
    duplicate_settings: removeDuplicates('duplicate_settings'),
    ignore_case: removeDuplicates('ignore_case'),
    sort_ascending: removeDuplicates('sort_ascending'),
    sort_descending: removeDuplicates('sort_descending'),
    apply: removeDuplicates('apply'),
    about_title: removeDuplicates('about_title'),
    about_desc: removeDuplicates('about_desc'),
    features_title: removeDuplicates('features_title'),
    feature_1_title: removeDuplicates('feature_1_title'),
    feature_1_desc: removeDuplicates('feature_1_desc'),
    feature_2_title: removeDuplicates('feature_2_title'),
    feature_2_desc: removeDuplicates('feature_2_desc'),
    feature_3_title: removeDuplicates('feature_3_title'),
    feature_3_desc: removeDuplicates('feature_3_desc'),
    feature_4_title: removeDuplicates('feature_4_title'),
    feature_4_desc: removeDuplicates('feature_4_desc'),
    feature_5_title: removeDuplicates('feature_5_title'),
    feature_5_desc: removeDuplicates('feature_5_desc'),
    feature_6_title: removeDuplicates('feature_6_title'),
    feature_6_desc: removeDuplicates('feature_6_desc'),
    faq_title: removeDuplicates('faq_title'),
    faq_1_title: removeDuplicates('faq_1_title'),
    faq_1_desc: removeDuplicates('faq_1_desc'),
    faq_2_title: removeDuplicates('faq_2_title'),
    faq_2_desc: removeDuplicates('faq_2_desc'),
    faq_3_title: removeDuplicates('faq_3_title'),
    faq_3_desc: removeDuplicates('faq_3_desc'),
    faq_4_title: removeDuplicates('faq_4_title'),
    faq_4_desc: removeDuplicates('faq_4_desc'),
    faq_5_title: removeDuplicates('faq_5_title'),
    faq_5_desc: removeDuplicates('faq_5_desc'),
    faq_6_title: removeDuplicates('faq_6_title'),
    faq_6_desc: removeDuplicates('faq_6_desc'),
    how_to_use_title: removeDuplicates('how_to_use_title'),
    step_1_title: removeDuplicates('step_1_title'),
    step_1_desc: removeDuplicates('step_1_desc'),
    step_2_title: removeDuplicates('step_2_title'),
    step_2_desc: removeDuplicates('step_2_desc'),
    step_3_title: removeDuplicates('step_3_title'),
    step_3_desc: removeDuplicates('step_3_desc'),
    step_4_title: removeDuplicates('step_4_title'),
    step_4_desc: removeDuplicates('step_4_desc'),
    use_cases_title: removeDuplicates('use_cases_title'),
    use_case_1_title: removeDuplicates('use_case_1_title'),
    use_case_1_desc: removeDuplicates('use_case_1_desc'),
    use_case_2_title: removeDuplicates('use_case_2_title'),
    use_case_2_desc: removeDuplicates('use_case_2_desc'),
    use_case_3_title: removeDuplicates('use_case_3_title'),
    use_case_3_desc: removeDuplicates('use_case_3_desc'),
    use_case_4_title: removeDuplicates('use_case_4_title'),
    use_case_4_desc: removeDuplicates('use_case_4_desc')
  };
};
